name: Rust Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Attempt to build
      run: cargo build --release

# uncomment the build step below to build on every change to master.

#     - name: Upload Release
#       uses: majkrzak/create-release@latest
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         name: master
#         code: master
#         body: Build of skyline-rs-template from master.
#         prerelease: true
#         recreate: true
#         assets: ./target/aarch64-skyline-switch/release/libskyline_rs_template.nro:libskyline_rs_template.nro:application/octet-stream
  

